MODULES = logical_ddl
PGFILEDESC = "logical_ddl - ddl replication over logical replication"

EXTENSION = logical_ddl
DATA = logical_ddl--0.1.sql

PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
